# Generated by Django 3.2.8 on 2022-04-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='modified',
        ),
    ]
