# Generated by Django 3.2.8 on 2022-04-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220406_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cluster_members',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
