# Generated by Django 3.2.8 on 2022-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cluster_cluster_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cluster_members',
            field=models.CharField(max_length=100),
        ),
    ]
