# Generated by Django 3.2.8 on 2022-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20220207_0834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Battallion_five',
        ),
        migrations.DeleteModel(
            name='Battallion_four',
        ),
        migrations.DeleteModel(
            name='Battallion_one',
        ),
        migrations.DeleteModel(
            name='Battallion_six',
        ),
        migrations.DeleteModel(
            name='Battallion_three',
        ),
        migrations.DeleteModel(
            name='Battallion_two',
        ),
        migrations.DeleteModel(
            name='Deleted_Employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='battallion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lower_level_incharge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='top_level_incharge',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Administration'), ('sponsor', 'Sponsor'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
