# Generated by Django 3.2.8 on 2022-04-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
    ]
