# Generated by Django 3.2.8 on 2022-04-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20220405_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('normal_user', 'Normal User'), ('mentor', 'Mentor'), ('premiuim_normal_user', 'Premiuim Normal User')], default='normal_user', max_length=32),
        ),
    ]
